version: '2.1'

services:
    db:
        image: postgres:10-alpine
        volumes:
            - /var/lib/postgresql/data
            # - ./src/init-db:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
    flyway:
        image: flyway/flyway
        command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=postgres -connectRetries=60 migrate
        volumes:
            - ./migrations/:/flyway/sql

        depends_on:
            - db 